FUTURE_REWARD_DISCOUNT = 0.99  # decay rate of past observations

SAVE_EVERY_X_STEPS = 600
LEARN_RATE = 0.00001
PRINT_STATISTICS_EVERY_X_STEPS = 100

SHOW_TRAINING = True
CHECKPOINT_PATH = './checkpoints'
SUMMARY_INTERVAL = 5
SUMMARY_PATH = './summaries'

EPISODES = 80000000
MINI_BATCH_SIZE = 1  # size of mini batches
EXPLORE_STEPS = 1000000


INITIAL_RANDOM_ACTION_PROB = 1.0  # starting chance of an action being random
STATE_FRAMES = 4  # number of frames to store in the state
RESIZED_SCREEN_X, RESIZED_SCREEN_Y = (80, 80)

STORE_SCORES_LEN = 200.

EXPERIMENT = 'Breakout-v0'
NUM_THREADS = 2

TARGET_NETWORK_UPDATE_FREQUENCY = 10000
NETWORK_UPDATE_FREQUENCY = 32

ENTROPY_BETA = 0.01
MAX_TIME_STEPS = 32






